### PR TITLE
Silkscreen is important for usability #25

### PR DESCRIPTION
**Pull request by rusefi**
Few bits of silk to get a taste of it

### CODE REVIEW

**Comment by rusefi** [comment]
image

**Comment by mck1117** [comment]
looks like lots of silk overlapping with components and other silk?

**Comment by rusefi** [comment]
@mck1117 please be more specific. What silk text would be an example of overlap?

**Comment by rusefi** [comment]
image

**Comment by mck1117** [comment]
this is being done as part of the single-sided relayout

**Pull request closed without merging**
